// Generates a sample dual-barcode QR card (NUX QR + DataMatrix metadata)
// Usage: npx tsx scripts/generate-sample-dual-qr.ts
import QRCode from 'qrcode'
import bwipjs from 'bwip-js'
import sharp from 'sharp'
import { writeFileSync } from 'fs'
import { buildQRString } from '../lib/server/qr-encoder'
import type { ProPresetParams } from '../lib/server/nux'

const VERSION = '1.5.2'
const OUT = '/mnt/nas-data/temp/kashmir-dual-qr-sample.png'
const PRESET_NAME = 'Jimmy Page - Kashmir'

// Kashmir — Jimmy Page, Danelectro 59, Hiwatt DR-103
const params: ProPresetParams = {
  device: 'plugpro',
  preset_name: PRESET_NAME,
  amp: { id: 6, gain: 52, master: 70, bass: 62, mid: 58, treble: 50, param6: 55 },
  cabinet: { id: 4, level_db: 0, low_cut_hz: 80, high_cut: 75 },
  noise_gate: { enabled: true, sensitivity: 28, decay: 35 },
  delay: { id: 4, enabled: true, p1: 48, p2: 32, p3: 20 },
  reverb: { id: 2, enabled: true, p1: 48, p2: 35, p3: 22 },
  master_db: 0,
}

// DataMatrix metadata — compact pipe-delimited format
// mai|version|make|model|inst-type|pu-layout|pu-sel|bridge:vol:tone|neck:vol:tone|preset-name
// Danelectro 59 has one master tone knob, both lipstick pickups active
const metadata = `mai|${VERSION}|dnl|59|g|ss|bn|ls:9:7|ls:8:7|${PRESET_NAME}`

async function generate() {
  // 1. NUX QR string → PNG buffer
  const qrString = buildQRString(params)
  const QR_PX = 400
  const qrBuffer = await QRCode.toBuffer(qrString, {
    errorCorrectionLevel: 'H',
    width: QR_PX,
    margin: 2,
    color: { dark: '#000000', light: '#ffffff' },
  })

  // 2. DataMatrix → PNG buffer
  const dmRaw: Buffer = await bwipjs.toBuffer({
    bcid:    'datamatrix',
    text:    metadata,
    scale:   3,
    padding: 2,
  })
  // Resize DataMatrix to fixed 80x80 for the card corner
  const DM_SIZE = 80
  const dmBuffer = await sharp(dmRaw).resize(DM_SIZE, DM_SIZE, { fit: 'contain', background: '#ffffff' }).png().toBuffer()
  const dmW = DM_SIZE
  const dmH = DM_SIZE

  // 3. Card dimensions — match QrImage canvas proportions
  const pad     = 36
  const headerH = 64
  const footerH = 96
  const w = QR_PX + pad * 2
  const h = QR_PX + headerH + footerH

  // 4. Header SVG
  const headerSvg = Buffer.from(
    `<svg width="${w}" height="${headerH}" xmlns="http://www.w3.org/2000/svg">
      <text x="${w / 2}" y="${headerH - 18}"
        font-family="system-ui,Arial,sans-serif" font-size="18" font-weight="500"
        fill="rgba(0,0,0,0.28)" text-anchor="middle">
        GENERATED BY MIGHTY AI QR  v${VERSION}
      </text>
    </svg>`
  )

  // 5. Footer SVG — preset name + device name, shifted left to leave room for DataMatrix
  const textMaxW = w - dmW - 24
  const footerSvg = Buffer.from(
    `<svg width="${w}" height="${footerH}" xmlns="http://www.w3.org/2000/svg">
      <text x="${textMaxW / 2}" y="32"
        font-family="system-ui,Arial,sans-serif" font-size="24" font-weight="600"
        fill="rgba(0,0,0,0.42)" text-anchor="middle">
        ${PRESET_NAME}
      </text>
      <text x="${textMaxW / 2}" y="56"
        font-family="system-ui,Arial,sans-serif" font-size="18" font-weight="500"
        fill="rgba(0,0,0,0.28)" text-anchor="middle">
        Mighty Plug Pro
      </text>
    </svg>`
  )

  // 6. Composite
  const dmTop  = headerH + QR_PX + Math.floor((footerH - dmH) / 2)
  const dmLeft = w - dmW - 12

  const image = await sharp({
    create: { width: w, height: h, channels: 4, background: '#ffffff' },
  })
    .composite([
      { input: headerSvg, top: 0,       left: 0    },
      { input: qrBuffer,  top: headerH, left: pad  },
      { input: footerSvg, top: headerH + QR_PX, left: 0 },
      { input: dmBuffer,  top: dmTop,   left: dmLeft },
    ])
    .png()
    .toBuffer()

  writeFileSync(OUT, image)
  console.log(`Written: ${OUT}`)
  console.log(`Card: ${w}x${h}px | DataMatrix: ${dmW}x${dmH}px`)
}

generate().catch(console.error)
